### ISSUE TITLE
Doesn't seem to work in a transclusion

### ISSUE THREAD

**Issue by ernstki** [ernstki/mediawiki-extensions-PlaceNewSection#1]
I'm not sure if this is solvable or not, but the `__TOC__` and `__NEWSECTIONLINK__` magic words seem to work fine when transcluded, `__ADDNEWSECTIONBELOW__` not so much.

For example, a template like this doesn't have the expected effect when it's transcluded into the lead of an article:

```
__TOC__ __NEWSECTIONLINK__ __ADDNEWSECTIONBELOW__
```

It may have to do with where we're hooking into the page rendering process with this extension. I don't have a clear path forward, so I'm just going to advise that it _not_ be transcluded.

## Workaround

Assuming a hypothetical Template:newsectiontop as shown above, put this in the article's lead section instead

```
{{subst:newsectiontop}}
```

…then save.

**Comment by In1quity** [comment]
Hello, I see problems with transclusion. Tell me, will the extension work with the "Start NewTopic" button that is included in the template? Like on this page: https://ru.wikipedia.org/wiki/Википедия:Форум/Правила

**Comment by ernstki** [comment]
> Tell me, will the extension work with the "Start NewTopic" button that is included in the template?

It's hard for me to say, since it appears the templates used on that page are deeply-nested, and the template names are also in Cyrillic, which makes it more of a challenge for me to translate enough to understand what's going on.

I only use MediaWiki (and this extension) on a private wiki for my team at work. I'm not familiar with any of the internals of how global Wikipedia sites are run. Do you have the ability to test the template and extension together in a non-production environment? That would be how I'd test it, on our internal wiki.

**Comment by In1quity** [comment]
Are you able to set up a public wiki so I can test these features? Unfortunately, I just don’t know how to set up a wiki myself.

**Comment by ernstki** [comment]
Sadly, no. I just have internal wikis.

**Comment by ernstki** [comment]
I'm going to go ahead and close this, just to leave a clean desk now that code's been [migrated to MWF's Gerrit](https://phabricator.wikimedia.org/T351776#9880286).

The workaround is a little annoying, but it's not an outright bug, and beyond my current capabilities to really dig into and fix the behavior anyway.
