### ISSUE TITLE
Clone repo to gerrit

### ISSUE THREAD

**Issue by In1quity** [ernstki/mediawiki-extensions-PlaceNewSection#3]
@ernstki Hello! Can you please clone your repository on gerrit as part of this task? 
https://phabricator.wikimedia.org/T344501

**Comment by In1quity** [comment]
Hi! Are you ok with gerrit, not with Gitlab for now? :) It's just that our engineers are silent and I'm not sure that they will answer in the near future :)

**Comment by In1quity** [comment]
@ernstki I can submit an application for you, but in order for you to have access to the repository, you need to register here (https://wikitech.wikimedia.org/) and update your profile on Phabricator :)

**Comment by ernstki** [comment]
OK, based on [recent activity in T351776](https://phabricator.wikimedia.org/T351776#9880286), it looks like this was done. Thanks for nudging me in the right direction.
